### ISSUE TITLE
App crashing with TypeError: Cannot read properties of null (reading 'abort') when calling drainGraphStream.abort() in replication scheduler

### ISSUE THREAD

**Issue by Powersource** [ssbc/ssb-tribes2-demo#10]
found here initially https://github.com/ssbc/ssb-tribes2/pull/135#issuecomment-1638030667 but seems to happen on `main` in this repo still

```
/home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/ssb-replication-scheduler@3.1.0_async-append-only-log@4.3.10/node_modules/ssb-replication-scheduler/index.js:121
    drainGraphStream.abort()
                     ^

TypeError: Cannot read properties of null (reading 'abort')
    at _pause (/home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/ssb-replication-scheduler@3.1.0_async-append-only-log@4.3.10/node_modules/ssb-replication-scheduler/index.js:121:22)
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/ssb-replication-scheduler@3.1.0_async-append-only-log@4.3.10/node_modules/ssb-replication-scheduler/index.js:138:25
    at trigger (/home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/obz@1.1.0/node_modules/obz/index.js:11:11)
    at Function.set (/home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/obz@1.1.0/node_modules/obz/index.js:54:7)
    at Object.reindexEncrypted (/home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/ssb-db2@7.1.1/node_modules/ssb-db2/core.js:993:20)
    at Object.hooked [as reindexEncrypted] (/home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/hoox@0.0.1/node_modules/hoox/index.js:10:15)
    at /home/me/prj/ssb/ssb-tribes2/listeners.js:142:22
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/levelup@4.4.0/node_modules/levelup/lib/levelup.js:220:5

Node.js v18.15.0
```

**Comment by Powersource** [comment]
curious if it happens after https://github.com/ssbc/ssb-tribes2/pull/139 I suspect it does.
