### ISSUE TITLE
Crash on Error: failed to get initial preferred epoch

### ISSUE THREAD

**Issue by Powersource** [ssbc/ssb-tribes2-demo#3]
I make a group, invite someone else and replicate etc a bit but then electron crashes with

```
Error: failed to get initial preferred epoch
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/ssb-tribes2@1.3.0_async-append-only-log@4.3.10/node_modules/ssb-tribes2/lib/epochs.js:271:44
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/ssb-tribes2@1.3.0_async-append-only-log@4.3.10/node_modules/ssb-tribes2/lib/epochs.js:255:23
  Error: Failed to resolve epoch @tangle/reduce
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/ssb-tribes2@1.3.0_async-append-only-log@4.3.10/node_modules/ssb-tribes2/lib/epochs.js:255:26
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/ssb-tribes2@1.3.0_async-append-only-log@4.3.10/node_modules/ssb-tribes2/lib/epochs.js:374:25
  Error: Failure collecting epoch messages
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/ssb-tribes2@1.3.0_async-append-only-log@4.3.10/node_modules/ssb-tribes2/lib/epochs.js:374:28
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/pull-stream@3.7.0/node_modules/pull-stream/sinks/reduce.js:10:5
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/pull-stream@3.7.0/node_modules/pull-stream/sinks/drain.js:26:24
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/pull-defer@0.2.3/node_modules/pull-defer/source.js:25:7
    at read.resolve (/home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/pull-defer@0.2.3/node_modules/pull-defer/source.js:20:13)
    at read.abort (/home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/pull-defer@0.2.3/node_modules/pull-defer/source.js:24:10)
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/ssb-tribes2@1.3.0_async-append-only-log@4.3.10/node_modules/ssb-tribes2/lib/epochs.js:461:36
  Error: Failed to get group init message
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/ssb-tribes2@1.3.0_async-append-only-log@4.3.10/node_modules/ssb-tribes2/lib/epochs.js:461:42
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/ssb-tribes2@1.3.0_async-append-only-log@4.3.10/node_modules/ssb-tribes2/lib/epochs.js:521:23
  Error: Failed to load group root with id ssb:message/classic/7MSEks6VKScWkYcNVQS97wNxg_zIUbT2_sOpwg7QwPI=
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/ssb-tribes2@1.3.0_async-append-only-log@4.3.10/node_modules/ssb-tribes2/lib/epochs.js:521:26
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/ssb-db2@7.1.1/node_modules/ssb-db2/core.js:243:18
  Error: Msg %7MSEks6VKScWkYcNVQS97wNxg/zIUbT2/sOpwg7QwPI=.sha256 not found in leveldb index
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/ssb-db2@7.1.1/node_modules/ssb-db2/core.js:243:21
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/ssb-db2@7.1.1/node_modules/ssb-db2/indexes/keys.js:34:16
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/levelup@4.4.0/node_modules/levelup/lib/levelup.js:192:14
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/encoding-down@6.3.0/node_modules/encoding-down/index.js:75:21

Node.js v18.15.0
```

**Comment by Powersource** [comment]
@mixmix do you want to grab this one?

**Comment by Powersource** [comment]
Haven't reproduced this one in a bit now. Might be related to me making sure that i always connect and follow before adding people to groups.

**Comment by Powersource** [comment]
might also get fixed by this? https://github.com/ssbc/ssb-tribes2/pull/134

**Comment by Powersource** [comment]
Gonna guess this is fixed now that we made the initial epoch getting more flexible
