### ISSUE TITLE
Crash onError: fatal error getting preferred epoch (membership case not handled yet)

### ISSUE THREAD

**Issue by Powersource** [ssbc/ssb-tribes2-demo#6]
Not sure which one this was but this should get solved once we handle more membership cases

```
/home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/github.com+ssbc+ssb-tribes2@c2e44dcf6911461a88fd482235aa2ada6117a5ef_async-append-only-log@4.3.10/node_modules/ssb-tribes2/listeners.js:175 Error: fatal error getting preferred epoch
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/github.com+ssbc+ssb-tribes2@c2e44dcf6911461a88fd482235aa2ada6117a5ef_async-append-only-log@4.3.10/node_modules/ssb-tribes2/listeners.js:175:52
    at buildPreferredEpoch (/home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/github.com+ssbc+ssb-tribes2@c2e44dcf6911461a88fd482235aa2ada6117a5ef_async-append-only-log@4.3.10/node_modules/ssb-tribes2/lib/epochs.js:567:17)
  Error: Membership case not handled yet
    at buildPreferredEpoch (/home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/github.com+ssbc+ssb-tribes2@c2e44dcf6911461a88fd482235aa2ada6117a5ef_async-append-only-log@4.3.10/node_modules/ssb-tribes2/lib/epochs.js:567:20)
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/github.com+ssbc+ssb-tribes2@c2e44dcf6911461a88fd482235aa2ada6117a5ef_async-append-only-log@4.3.10/node_modules/ssb-tribes2/lib/epochs.js:257:7
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/github.com+ssbc+ssb-tribes2@c2e44dcf6911461a88fd482235aa2ada6117a5ef_async-append-only-log@4.3.10/node_modules/ssb-tribes2/lib/epochs.js:381:9
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/pull-stream@3.7.0/node_modules/pull-stream/sinks/reduce.js:10:5
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/pull-stream@3.7.0/node_modules/pull-stream/sinks/drain.js:26:24
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/pull-stream@3.7.0/node_modules/pull-stream/throughs/async-map.js:28:19
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/pull-stream@3.7.0/node_modules/pull-stream/throughs/flatten.js:35:20
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/pull-stream@3.7.0/node_modules/pull-stream/sources/values.js:19:7
    at nextStream (/home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/pull-stream@3.7.0/node_modules/pull-stream/throughs/flatten.js:33:9)
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/pull-stream@3.7.0/node_modules/pull-stream/throughs/flatten.js:22:31
```

**Comment by Powersource** [comment]
yeah this is a known tribes2 bug so closing this here
