### ISSUE TITLE
Error: Failed finding new preferred epochs when looking for them to add missing members to or when checking if an epoch is missing

### ISSUE THREAD

**Issue by Powersource** [ssbc/ssb-tribes2-demo#7]
Getting this in the console for a person who gets added to the group. I was on the epoch-recovery branch but I think it happened on main too.

```
/home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/github.com+ssbc+ssb-tribes2@c2e44dcf6911461a88fd482235aa2ada6117a5ef_async-append-only-log@4.3.10/node_modules/ssb-tribes2/listeners.js:283 Error: Failed finding new preferred epochs when looking for them to add missing members to or when checking if an epoch is missing
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/github.com+ssbc+ssb-tribes2@c2e44dcf6911461a88fd482235aa2ada6117a5ef_async-append-only-log@4.3.10/node_modules/ssb-tribes2/listeners.js:283:52
  Error: failed to get initial preferred epoch
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/github.com+ssbc+ssb-tribes2@c2e44dcf6911461a88fd482235aa2ada6117a5ef_async-append-only-log@4.3.10/node_modules/ssb-tribes2/lib/epochs.js:271:44
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/github.com+ssbc+ssb-tribes2@c2e44dcf6911461a88fd482235aa2ada6117a5ef_async-append-only-log@4.3.10/node_modules/ssb-tribes2/lib/epochs.js:255:23
  Error: Failed to resolve epoch @tangle/reduce
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/github.com+ssbc+ssb-tribes2@c2e44dcf6911461a88fd482235aa2ada6117a5ef_async-append-only-log@4.3.10/node_modules/ssb-tribes2/lib/epochs.js:255:26
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/github.com+ssbc+ssb-tribes2@c2e44dcf6911461a88fd482235aa2ada6117a5ef_async-append-only-log@4.3.10/node_modules/ssb-tribes2/lib/epochs.js:374:25
  Error: Failure collecting epoch messages
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/github.com+ssbc+ssb-tribes2@c2e44dcf6911461a88fd482235aa2ada6117a5ef_async-append-only-log@4.3.10/node_modules/ssb-tribes2/lib/epochs.js:374:28
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/pull-stream@3.7.0/node_modules/pull-stream/sinks/reduce.js:10:5
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/pull-stream@3.7.0/node_modules/pull-stream/sinks/drain.js:26:24
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/pull-defer@0.2.3/node_modules/pull-defer/source.js:25:7
    at read.resolve (/home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/pull-defer@0.2.3/node_modules/pull-defer/source.js:20:13)
    at read.abort (/home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/pull-defer@0.2.3/node_modules/pull-defer/source.js:24:10)
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/github.com+ssbc+ssb-tribes2@c2e44dcf6911461a88fd482235aa2ada6117a5ef_async-append-only-log@4.3.10/node_modules/ssb-tribes2/lib/epochs.js:461:36
  Error: Failed to get group init message
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/github.com+ssbc+ssb-tribes2@c2e44dcf6911461a88fd482235aa2ada6117a5ef_async-append-only-log@4.3.10/node_modules/ssb-tribes2/lib/epochs.js:461:42
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/github.com+ssbc+ssb-tribes2@c2e44dcf6911461a88fd482235aa2ada6117a5ef_async-append-only-log@4.3.10/node_modules/ssb-tribes2/lib/epochs.js:521:23
  Error: Failed to load group root with id ssb:message/classic/1XBrerh93PH8H2n6RlXLAUf35fQqeqmP1Wji-JvHaWo=
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/github.com+ssbc+ssb-tribes2@c2e44dcf6911461a88fd482235aa2ada6117a5ef_async-append-only-log@4.3.10/node_modules/ssb-tribes2/lib/epochs.js:521:26
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/ssb-db2@7.1.1/node_modules/ssb-db2/core.js:243:18
  Error: Msg %1XBrerh93PH8H2n6RlXLAUf35fQqeqmP1Wji+JvHaWo=.sha256 not found in leveldb index
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/ssb-db2@7.1.1/node_modules/ssb-db2/core.js:243:21
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/ssb-db2@7.1.1/node_modules/ssb-db2/indexes/keys.js:34:16
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/levelup@4.4.0/node_modules/levelup/lib/levelup.js:192:14
    at /home/me/prj/ssb/ssb-tribes2-demo/node_modules/.pnpm/encoding-down@6.3.0/node_modules/encoding-down/index.js:75:21
```

**Comment by Powersource** [comment]
Doesn't seem to break too many things but probably makes the crash recovery not work (and therefore untestable)

**Comment by Powersource** [comment]
hopefully fixed by https://github.com/ssbc/ssb-tribes2/pull/134
